### ISSUE TITLE
Possible missing files..

### ISSUE THREAD

**Issue by ZhangAoCanada** [AIBluefisher/DOGS#7]
Hello, Thanks for your excellent work, especially on the data partition of large scale. 
When trying to reimplement your work, I noticed there might be some files missing. 

The config files for urban3d and matrixcity are not provided in the repo.....
Also, in order to convert matrix city to colmap, one has to offer something like `database.db`, which is not provided in the original dataset....

Could you share your spare time to solve these issues? thanks in advance.

**Comment by AIBluefisher** [comment]
Hi, sorry for the inconvenience. We just released the configuration file for the urbanscene3d dataset. To convert the matrix city to colmap, try to run `./scripts/preprocess/colmap_mapping.sh` while comment the command at line 42-47 to extract features and matches.
We are still brewing rest of the code, mainly on refactoring the ADMM related training code and corresponding license for correct usage of this project. It may still take a week to finish it.

**Comment by ZhangAoCanada** [comment]
> Hi, sorry for the inconvenience. We just released the configuration file for the urbanscene3d dataset. To convert the matrix city to colmap, try to run `./scripts/preprocess/colmap_mapping.sh` while comment the command at line 42-47 to extract features and matches. We are still brewing rest of the code, mainly on refactoring the ADMM related training code and corresponding license for correct usage of this project. It may still take a week to finish it.

Thank you!
